config/routes.rb
Rails.application.routes.draw do
  root 'application#top'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get "profile/:id", to: "users#profile", as: 'user_profile'
  patch	"profile/:id", to: "users#profile_update"
  resources :rooms do
    collection do
      get :post
      get :search
    end
  end
  resources :reserves
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :room
  validates :start,    presence: true
  validates :end, presence: true
  validates :price,   presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reserves
  validates :name,    presence: true
  validates :content, presence: true
  validates :price,   presence: true
  validates :address, presence: true
  validates :image,   presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  mount_uploader :image, ImageUploader
  has_secure_password
  has_many :rooms
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :current_password, presence: true, on: [:update]
  validates :name,    presence: true, on: [:update]
  validates :image,   presence: true, on: [:update]
  validates :content, presence: true, on: [:update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_q
  before_action :header_image
  before_action :login_required
  skip_before_action :login_required, only: [:top]

  def top
  end

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

  def set_q
    @q = Room.ransack(params[:q])
  end

  def header_image
    @image = User.find(current_user.id) if logged_in?
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def index
    @reserves = Reserve.all
  end

  def new
    @room = Room.find(params[:room_id])
    @reserve = Reserve.new(reserve_params)
    if (params[:reserve][:start] == "") || (params[:reserve][:end] == "") || (params[:reserve][:people] == "")
      flash[:alert] = "人数は必須です"
      redirect_to request.referrer
    elsif @reserve.end < Date.today
      flash[:alert] = "過去の日付は無効です"
      redirect_to request.referrer
    elsif params[:reserve][:start] > params[:reserve][:end]
      flash[:alert] = "終了日は開始日より後にしてください"
      redirect_to request.referrer
    end

  end

  def create
    @room = Room.find(params[:room_id])
    @reserve = Reserve.new(reserve_params)
    @reserve.room_id = @room.id
    @reserve.people = params[:people]
    @reserve.save
    flash[:notice] = "Reservation was successfully created."
    redirect_to reserf_path(@reserve.id)
  end

  def show
    @reserve = Reserve.find(params[:id])
  end
  
  private

  def reserve_params
    params.require(:reserve).permit(:start, :end, :price, :people)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @rooms = Room.all
  end
  
  def search
    @rooms = @q.result
  end

  def post
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    # return render :new if @room.invalid?
    if @room.save
      flash[:notice] = "Room was successfully created."
      redirect_to room_path(@room.id)
    else
      return render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reserve = Reserve.new
  end

  private

  def room_params
    params.require(:room).permit(:name, :content, :price, :address, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully."
      redirect_to root_path
    else
      # ログイン失敗した場合
      flash.now[:danger] = 'Invalid Email or password.'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Signed out successfully.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:index, :new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    password = params[:user][:current_password]
    if @user.authenticate(password)
      @user.current_password = current_user.password_digest
      @user.update(user_params)
      @user.current_password = nil
      flash[:notice] = "ユーザーIDが「#{@user.id}」の情報を更新しました"
      redirect_to user_path(@user.id)
    else
      @user.current_password = nil
      @user.update(user_params)
      render :edit
    end
  end
  
  def profile
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_profile_path(current_user.id)
    end
  end

  def profile_update
    @user = User.find_by(id: params[:id])
    @user.current_password = current_user.password_digest
    if @user.update(profile_params)
      @user.current_password = nil
      flash[:notice] = "Profile was successfully updated."
      redirect_to user_profile_path(@user.id)
    else
      @user.current_password = nil
      render :profile
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :content)
  end

  def profile_params
    params.require(:profile).permit(:email, :name, :image, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/top.html.erb
<div class="top-main">
  <div class="container">
    <div class="row col-6">
      <div class="form-fream">
        <div class="form-area">
          <p class="form-area-title">Potepan Shareでまだ体験したことのない旅をしよう</p>
          <%= search_form_for @q, url: search_rooms_path do |f| %>
            <div><%= f.label :address, "エリア" %></div>
            <div><%= f.search_field :address_cont, placeholder: "東京", class: "form-control mb-4" %></div>
            <div><%= f.submit "探す", class:"btn btn-primary form-control" %></div>
          <% end %>
        </div>
      </div> 
    </div>
  </div>
</div>
<div class="container">
  <div class="panel-area">
    <h1 class="section-title">おすすめのエリア</h1>
    <div class="row">
      <div class="col-3 panel">
        <%= link_to image_tag("img_tokyo.jpg", class: "panel-image"), post_rooms_path %>
        <p class="panel-write">東京</p>
      </div>
      <div class="col-3">
        <%= link_to image_tag("img_osaka.jpg", class: "panel-image"), post_rooms_path %>
        <p class="panel-write">大阪</p>
      </div>
      <div class="col-3">
        <%= link_to image_tag("img_kyoto.jpg", class: "panel-image"), post_rooms_path %>
        <p class="panel-write">京都</p>
      </div>
      <div class="col-3">
        <%= link_to image_tag("img_sapporo.jpg", class: "panel-image"), post_rooms_path %>
        <p class="panel-write">札幌</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReservationApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
  </head>

  <body>

    <header>
    <div class="left-header">
      <%= link_to image_tag("logo.png"), "/" %>
      <%= search_form_for @q, url: search_rooms_path do |f| %>
        <%= f.search_field :address_cont, placeholder: "\uf3c5 エリア", class: "fa" %>
        <%= f.search_field :name_or_content_cont, placeholder: "\uf002 キーワード", class: "fa" %>
        <%= f.submit class: "d-none" %>
      <% end %>
    </div>
    <div class="right-header">
      <% if logged_in? %>
        <div class="right-header-top">
          <div class="image-header" onclick=eventA();>
            <% if @image.image.blank? %>
              <%= image_tag "default_icon.jpg", class: "header-icon", alt: "メニュ" %>
            <% else %>
              <%= image_tag @image.image.url, class: "header-icon", alt: "メニュ" %>
            <% end %>
         </div>
          <div class="header-font"><%= current_user.name %></div>
        </div>
      <% else %>
        <div class="right-header-login">
          <%= link_to "ログイン", new_session_path, class: "btn btn-primary mx-3" %>
          <%= link_to "登録する", new_user_path, class: "btn btn-dark"%>
        </div>
      <% end %>

    </div>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="top">
      <%= yield %>
      12
      <% if logged_in? %>
      <ul id="header-nav-menu" class="header-nav-menu-none">
        <li><%= link_to "ルーム登録", new_room_path %></li>
        <li><%= link_to "予約済みルーム一覧", reserves_path %></li>
        <li><%= link_to "登録済みルーム一覧", post_rooms_path %></li>
        <li><%= link_to "設定", user_path(current_user.id) %></li>
        <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
      </ul>
      <% end %>
    </div>
    <footer>
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

<script>
  eventA = function() {
    const testa = document.getElementById('header-nav-menu');
    if (testa.classList.contains('header-nav-menu-none')) {
      testa.classList.remove('header-nav-menu-none');
    } else {
      testa.classList.add('header-nav-menu-none');
    }
  }
</script>

app/views/reserves/index.html.erb
<div class="reservations user-nav">
<h4 class="pb-4">予約済みルーム一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>合計料金</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>予約確定日時</th>
    </tr>
  </thead>
  <tbody>
    <% @reserves.each do |reserve| %>
      <tr>
        <td class="image-td"><%= image_tag reserve.room.image.url, class: "reservations-image" %></td>
        <td class="room-name"><%= link_to reserve.room.name,  room_path(reserve.room.id) %></td>
        <td><%= reserve.room.content %></td>
        <td class="reserve-price"><%= reserve.price %></td>
        <td><%= reserve.start %></td>
        <td><%= reserve.end %></td>
        <td><%= reserve.created_at %></td>
      </tr>
    <% end %>  
  </tbody>
</table>
</div>

app/views/reserves/new.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">

      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon"><%= @room.price %> / 日</h5>
        
        <div class="reservations-new-date-select">
        <%= form_with model: @reserve, local: true do |f| %>
          <div>
            <div><%= f.label :start, "開始日" %></div>
            <%= f.text_field :start, readonly: true, class: "form-control" %>
          </div>
          <div>
            <div><%= f.label :end, "終了日" %></div>
            <%= f.text_field :end, readonly: true, class: "form-control" %>
          </div>
          <% day = ((@reserve.end - @reserve.start) / 86400).floor %>
          <% number = @reserve.people %>

          <h6 class="reservations-new-check-content">使用日数 : <%= day %>日</h6>
          <h6 class="reservations-new-check-content">人数 : <%= number %>人</h6>
          <div>
            <div><%= f.label :price, "合計金額" %></div>
            <%= f.text_field :price, value: @room.price * day * number, readonly: true, class: "form-control" %>
          </div>
          <%= hidden_field_tag :room_id, @room.id %>
          <%= hidden_field_tag :people, number %>
        
          <p>上記内容でよろしければ「予約を確定」を押してください</p>
          <%= f.submit "予約を確認", class: "form-control btn btn-primary" %>
          <%= link_to "ルーム詳細に戻る", request.referrer, class: "form-control btn btn-secondary" %>
        <% end %>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/reserves/show.html.erb
<p>予約した部屋</p>
<%= @reserve.people %>
<p>開始日</p>
<%= @reserve.start %>
<p>終了日</p>
<%= @reserve.end %>
<p>価格</p>
<%= @reserve.price %>円

app/views/rooms/index.html.erb
<div class="reservations">
  <h4 class="pb-4">検索結果：<%= @rooms.count %>件</h4>
  
  <div class="row">
    
    <% @rooms.each do |room| %>
      <%= link_to room_path(room.id), class:"card-room" do %>
      <div class="col-3 cards">
        <div class="card">
          <div class="image">
            <%= image_tag room.image.url, class: "image-size" %>
          </div>
          <div class="room-profile">
            <p class="profile-font"><%= room.name %></p>
            <p class="profile-font2"><%= room.address %></p>
            <p class="profile-font3"><%= room.price %></p>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="row user-nav">
  <div class="col-2 room-nav">
    <ul>
      <li class="active active-place"><%= link_to "基本情報", new_room_path, class: "active-font" %></li>
    </ul>
  </div>
  
  <div class="col-10 room-view">
    <div class="room-view-box">
      <%= form_with model: @room, local: true do |f| %>
        
        <div class="update-content">
          <h5>ルーム情報登録</h5>
        </div>
        
        <div class="update-content">
          <div class="row">
            <p class="col-3 required-a">ルーム名</p>
            <%= f.text_field :name, placeholder: "ルーム名を入力", class: "col-9 form-control" %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <p class="col-3 required-a">ルーム紹介</p>
            <%= f.text_area :content, placeholder: "ルーム説明を入力", class: "col-9 form-control" %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <p class="col-3 required-a">料金</p>
            <%= f.number_field :price, placeholder: "1日あたりの料金を入力", class: "col-9 form-control" %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <p class="col-3 required-a">住所</p>
            <%= f.text_field :address, placeholder: "住所を入力", class: "col-9 form-control" %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <p class="col-3 required-a">ルーム画像</p>
            <%= f.file_field :image, class: "col-9" %>
          </div>
        </div>

        <div class="update-content">
          <%= f.submit "登録", class: "col-md-2 btn btn-primary" %>
        </div>
    
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/post.html.erb
<div class="reservations user-nav">

    <h4 class="pb-4">登録済みルーム一覧</h1>
    <table class="table-size">
      <thead>
        <tr>
          <th>ルーム画像</th>
          <th>ルーム名</th>
          <th>ルーム紹介</th>
          <th>料金</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td class="image-td"><%= image_tag room.image.url, class: "reservations-image" %></td>
            <td class="room-name">
              <%= link_to room.name, room_path(room.id) %>
            </td>
            <td><%= room.content %></td>
            <td>¥<%= room.price %></td>
            <td><%= room.created_at %></td>
          </tr>
        <% end %>
      </tbody>  
    </table>

</div>

app/views/rooms/search.html.erb
<div class="reservations">
  <h4 class="pb-4">検索結果：<%= @rooms.count %>件</h4>
  
  <div class="row">
    
    <% @rooms.each do |room| %>
      <%= link_to room_path(room.id), class:"card-room" do %>
      <div class="col-3 cards">
        <div class="card">
          <div class="image">
            <%= image_tag room.image.url, class: "image-size" %>
          </div>
          <div class="room-profile">
            <p class="profile-font"><%= room.name %></p>
            <p class="profile-font2"><%= room.address %></p>
            <p class="profile-font3"><%= room.price %></p>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-8">

      <%= image_tag @room.image.url, class: "room-show-image" %>

      <div class="room-show-detile">
        <div class="room-show-icon">
          <%= image_tag 'default_icon.jpg', class: "room-icon" %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%= @room.name %></p>
          <p class="room-show-profile-address"><%= @room.address %></p>
        </div>
      </div>
      <p class="room-show-detile-content"><%= @room.content %></p>
    </div>
    
    <div class="col-4">
    <div class="room-show-nav">
      <h5 class="price-icon"><%= @room.price %> / 日</h5>
        <div class="room-show-date-select">
        <%= form_with(scope: :reserve, url: new_reserf_path, method: :get, local: true) do |f| %>
          <div>
            <div><%= f.label :start, "開始日", class: "show-font" %></div>
            <%= f.date_field :start, class: "form-control mb-4" %>
          </div>
          <div>
            <div><%= f.label :end, "終了日", class: "show-font" %></div>
            <%= f.date_field :end, class: "form-control mb-4" %>
          </div>
          <div>
            <div><%= f.label :people, "人数", class: "show-font" %></div>
            <%= f.number_field :people, class: "form-control mb-4" %>
          </div>
          <%= hidden_field_tag :room_id, @room.id %>
        
          <%= f.submit "予約する", class: "form-control btn btn-primary" %>
        <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_error.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <% object.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_list.html.erb
<div>
  <ul class="list-group">
    <li class="list-group-item">An item</li>
    <li class="list-group-item">A second item</li>
    <li class="list-group-item">A third item</li>
    <li class="list-group-item">A fourth item</li>
    <li class="list-group-item">And a fifth one</li>
  </ul>
</div>

app/views/users/edit.html.erb
<div class="container form">
  <div class="edit-form">

    <%= form_with model: @user, local: true do |f| %>
      <h2>アカウント編集</h2>
      <%= render "shared/error", object: @user %>
      <div class="field">
        <%= f.label :email, "メールアドレス", class: "edit-font" %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password, "変更後パスワード（変更する場合のみ入力）", class: "edit-font" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, "パスワード確認用（変更する場合のみ入力）", class: "edit-font" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :current_password, "現在のパスワード", class: "edit-font" %>
        <%= f.password_field :current_password, placeholder: "現在のパスワードを入力", class: "form-control" %>
      </div>
      <div class="field"><%= f.submit "更新", class: "form-control btn btn-primary" %></div>
      <div class="field"><%= link_to "戻る", user_path(@user.id), class: "form-control text-decoration" %></div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
ギータのくびったけ

app/views/users/new.html.erb
<div class="container device">
  <div class="device_frame">
    <p class="my-4">新しいアカウントを作成</p>
    <%= form_with model: @user, local: true, class: "new-user" do |f| %>
      <%= render "shared/error", object: @user %>
      
      <div class="form-row">
        <div class="required-b col-2"></div>
        <%= f.text_field :name, class: "form-control col-10", placeholder: "ユーザー名" %>
      </div>
      
      <div class="form-row">
        <div class="required-b col-2"></div>
        <%= f.email_field :email, class: "form-control col-10", placeholder: "メールアドレス" %>
      </div>
      
      <div class="form-row">
        <div class="required-b col-2"></div>
        <%= f.password_field :password, class: "form-control col-10", placeholder: "パスワード" %>
      </div>
      
      <div class="form-row">
        <div class="required-b col-2"></div>
        <%= f.password_field :password_confirmation, class: "form-control col-10", placeholder: "パスワード確認" %>
      </div>
      
      <div>
        <%= f.submit "新しいアカウントを作成", class: "form-control btn-primary my-4 " %>
      </div>
    <% end %>
    <%= link_to "すでにアカウントをお持ちの方はログイン", new_session_path %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="row user-nav">
  <div class="col-2 room-nav">
    <ul>
      <li class="active"><%= link_to "アカウント", user_path(current_user.id) %></li>
      <li class="active active-place"><%= link_to "プロフィール", user_profile_path(current_user.id), class: "active-font" %></li>
    </ul>
  </div>
  
  <div class="col-10 room-view">
    <div class="room-view-box">
      <%= form_with(scope: :profile, url: user_profile_path, method: :patch, local: true) do |f| %>
        
        <div class="update-content">
          <h5>プロフィール</h5>
        </div>
        
        <div class="update-content">
          <% if @user.image.blank? %>
            <div class="center-icon"><%= image_tag "default_icon.jpg", class: "icon-center" %></div>
          <% else %>
           <div class="center-icon"><%= image_tag @user.image.url, class: "icon-center" %></div>
          <% end %>
        </div>

        <div class="update-content">
          <div class="row">
            <%= f.label :image, "アイコン画像", class: "col-3 required-a" %>
            <% if @user.image.blank? %>
              <div class="field_with_errors"><%= f.file_field :image, class: "col-9" %></div>
            <% else %>
              <%= f.file_field :image, class: "col-9" %>
            <% end %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <%= f.label :name, "名前", class: "col-3 required-a" %>
            <% if @user.name.blank? %>
              <div class="field_with_errors"><%= f.text_field :name, placeholder: "名前を入力", class: "col-9 form-control" %></div>
            <% else %>
              <%= f.text_field :name, placeholder: "名前を入力", class: "col-9 form-control" %>
            <% end %>
          </div>
        </div>

        <div class="update-content">
          <div class="row">
            <%= f.label :content, "自己紹介", class: "col-3 required-a" %>
            <% if @user.content.blank? %>
              <div class="field_with_errors"><%= f.text_area :content, placeholder: "自己紹介を入力", class: "col-9 form-control" %></div>
            <% else %>
              <%= f.text_area :content, placeholder: "自己紹介を入力", class: "col-9 form-control" %>
            <% end %>
          </div>
        </div>

        <div class="update-content">
          <%= f.submit "更新", class: "col-md-2 btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row user-nav">
  <div class="col-2 room-nav">
    <ul>
      <li class="active active-place"><%= link_to "アカウント", user_path(current_user.id), class: "active-font" %></li>
      <li class="active"><%= link_to "プロフィール", user_profile_path(current_user.id) %></li>
    </ul>
  </div>
  
  <div class="col-10 room-view">
    <div class="room-view-box">

        
      <div class="update-content">
        <h5>アカウント</h5>
      </div>
      
      <div class="update-content">
        <div class="row">
          <div class="col-3 account-font">メールアドレス</div>
          <div class="col-9"><%= @user.email %></div>
        </div>
      </div>   
      
      <div class="update-content">
        <div class="row">
          <div class="col-3 account-font">パスワード</div>
          <div class="col-9">********</div>
        </div>
      </div>
      
      <div class="update-content">
        <%= link_to "編集", edit_user_path(current_user.id), class: "col-md-2 btn btn-primary" %>
      </div>
    </div>
  </div>
</div>